[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.141"
redis-queue-rs = "0.1.7"
redis = "0.29.0"
once_cell = "1.21.3"
uuid = "1.18.0"
